version: '3.9'
services:
  backend-go:
    build: ./backend-go
    command: [ "/app/server" ]
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./backend-go:/app
    depends_on: []

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8080
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-go

  backend-cpp:
    build: ./backend-cpp
    ports:
      - "9090:9090"
    volumes:
      - ./backend-cpp:/app
    depends_on: []
